global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8888']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Ejemplo para scrapear métricas de otros contenedores que expongan un endpoint /metrics
  # - job_name: 'mi-aplicacion'
  #   static_configs:
  #     - targets: ['mi-app-container-name:8000']