version: '3.1'

services:
  angular-app:
    restart: always
    container_name: angular-prod
    image: node:14.16.1
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 9091:8000
    command: [ sh, -c, "cd application/app && npm install && npm install -g bower && bower install --force-latest --allow-root && npm run dev" ]
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - bower
    expose:
      - 8000

  # bower:
  #   restart: always
  #   container_name: bower
  #   image: node:14.16.1
  #   working_dir: /frontend
  #   volumes:
  #     - .:/frontend
  #   command: npm install -g bower && bower install --allow-root 

  nginx:
    container_name: nginx-prod
    restart: always
    image: nginx:1.17-alpine
    volumes:
      - ./application/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./application/api-lumen/app/public:/var/www/html/app/public
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "83:83"
  php:
    container_name: php-prod
    restart: always
    build: application/api-lumen
    volumes:
      - ./application/api-lumen:/var/www/html
    working_dir: /var/www/html/app
    command: sh -c "ls && composer install --no-dev --optimize-autoloader && php -S 0.0.0.0:9001 -t public"
    links:
      - db
      - cache
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db-prod
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    ports:
      - "9001:9001"
    expose:
      - 9001

  cors:
    restart: always
    build:
      context: ./application/nginx
      dockerfile: Dockerfile
    container_name: cors-prod
    ports:
      - "4546:83"

  db:
    container_name: db-prod
    image: mysql:8.0.36
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./db_init_scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    expose:
      - 33006

  adminer:
    container_name: adminer-prod
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT}:8080

  cache:
    restart: always
    container_name: cache-prod
    image: memcached:1.6-alpine

volumes:
  mysql_data:
    name: lextracking_db_prod