version: '3.1'

services:

  angular-app:
    restart: always
    container_name: angular
    image: node:14.16.1
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 9090:8000
    command: [sh, -c, "cd application/app && npm install -g bower && bower install --allow-root && npm run dev"]
    environment:
      - NODE_ENV=development
    expose:
      - 9090

  nginx:
    container_name: nginx
    image: nginx:1.17-alpine
    volumes:
      - ./application/nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./application/api-lumen/app/public:/var/www/html/app/public
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "82:82"
  php:
    container_name: php
    build: application/api-lumen
    volumes:
      - ./application/api-lumen:/var/www/html
    command: php-fpm
    working_dir: /var/www/html/app/public
    links:
      - db
      - cache
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    ports:
      - "9000:9000"

  db:
    container_name: db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    expose:
      - 3306

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  cache:
    container_name: cache
    image: memcached:1.6-alpine