version: '3.8'

services:
  frontend:
    networks:
      - app-network
    env_file:
      - ../env_files/.env.prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    networks:
      - app-network
    env_file:
      - ../env_files/.env.prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  database:
    networks:
      - app-network
    env_file:
      - ../env_files/.env.prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay