version: '3.8'

services:
  frontend:
    platform: linux/amd64
    restart: always
    build:
      context: ../services/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "9081:80"
    env_file:
      - ../env_files/.env.dev

  app-react:
      restart: always
      build:
        context: ../services/app-react
        dockerfile: Dockerfile.dev
        args:
          - VITE_BASE_URL=${VITE_BASE_URL}
          - VITE_BASE_PHOTO=${VITE_BASE_PHOTO}
      env_file:
      - ../env_files/.env.dev
      volumes:
        - ../services/app-react/src:/app/src
      ports:
        - 5181:5173

  nginx:
    build:
      context: ../services/nginx
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - ../env_files/.env.dev
    volumes:
      - ../services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../services/backend/app:/var/www/html
    ports:
      - "83:82"

  backend:
    build:
      context: ../services/backend
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - ../env_files/.env.dev
    volumes:
      - ../services/backend/app:/var/www/html
      - vendor_data:/var/www/html/vendor
    ports:
      - "3086:9000"
    expose: 
        - 9000
    
  chatbot:
    build:
        context: ../services/chatbot
        dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - ../env_files/.env.dev
    volumes:
      - ../services/chatbot/src:/app/src
    ports:
      - "3081:3000"
    expose: 
        - 3000

  database:
    restart: always
    env_file:
      - ../env_files/.env.dev
    ports:
      - ${DB_EXTERNAL_PORT}:33006
    expose: 
        - 33006
    volumes:
      - ../services/database/db_init_scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  vendor_data:
  mysql_data: