version: '3.8'

services:
  frontend:
    platform: linux/amd64
    build:
      context: ../services/frontend
      dockerfile: Dockerfile.prod
    ports:
      - "9091:80"
    env_file:
      - ../env_files/.env.prod
    volumes:
      - ../services/frontend/src:/app/src

  nginx:
    build:
      context: ../services/nginx
      dockerfile: Dockerfile.prod
    env_file:
      - ../env_files/.env.prod
    volumes:
      - ../services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../services/backend/app:/var/www/html
    ports:
      - "83:82"

  backend:
    build:
      context: ../services/backend
      dockerfile: Dockerfile.prod
    env_file:
      - ../env_files/.env.prod
    volumes:
      - ../services/backend/app:/var/www/html
      - vendor_data:/var/www/html/vendor
    ports:
      - "9000:9000"
    expose: 
        - 9000

  chatbot:
    build:
        context: ../services/chatbot
        dockerfile: Dockerfile.prod
    env_file:
      - ../env_files/.env.prod
    volumes:
      - ../services/chatbot/src:/app/src
    ports:
      - "3000:3000"
    expose: 
        - 3000

  database:
    restart: always
    env_file:
      - ../env_files/.env.prod
    ports:
      - ${DB_EXTERNAL_PORT}:33006
    expose: 
        - 33006
    volumes:
      - ../services/database/db_init_scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  vendor_data:
  mysql_data: