version: '3.8'

services:
  frontend:
    platform: linux/amd64
    restart: always
    build:
      context: ../services/frontend
      dockerfile: Dockerfile.local
    ports:
      - "9080:8000"
      - "35729:35729"
    env_file:
      - ../env_files/.env.local
    volumes:
      - ../services/frontend/src:/app/src
  
  app-react:
      restart: always
      build:
        context: ../services/app-react
        dockerfile: Dockerfile.local
      volumes:
        - ../services/app-react/src:/app/src
      ports:
        - 5180:5173

  nginx:
    build:
      context: ../services/nginx
      dockerfile: Dockerfile.local
    restart: always
    env_file:
      - ../env_files/.env.local
    volumes:
      - ../services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../services/backend/app:/var/www/html
    ports:
      - "82:82"

  backend:
    build:
      context: ../services/backend
      dockerfile: Dockerfile.local
    restart: always
    env_file:
      - ../env_files/.env.local
    volumes:
      - ../services/backend/app:/var/www/html
      - vendor_data:/var/www/html/vendor
    ports:
      - "3085:9000"
    expose: 
        - 9000
  
  chatbot:
    restart: always
    build:
        context: ../services/chatbot
        dockerfile: Dockerfile.local
    env_file:
      - ../env_files/.env.local
    volumes:
      - ../services/chatbot/src:/app/src
    ports:
      - "3080:3000"
    expose: 
        - 3000

  database:
    restart: always
    env_file:
      - ../env_files/.env.local
    ports:
      - ${DB_EXTERNAL_PORT}:33006
    expose: 
        - 33006
    volumes:
      - ../services/database/db_init_scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  vendor_data:
  mysql_data: