services:
  test-app:
    image: node:20
    working_dir: /app
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
    # Montamos todo el directorio actual en /app dentro del contenedor
    volumes:
      - .:/app
    # Aseguramos que instale dependencias si es necesario y corra los tests
    command: sh -c "npm install && npm run test"
