FROM node:20-alpine

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --chown=appuser:appgroup package*.json ./

#RUN npm ci --only=production
RUN npm install

COPY --chown=appuser:appgroup . .

USER appuser

EXPOSE 3000

CMD [ "npm", "run", "dev" ]