name: SonarQube Analysis

on:
  push:
    branches:
      #- main
      - dev
  pull_request:
    branches:
      #- main
      - dev
jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      #-- CODIGO CUSTOM --#
      
      # NO INSTALL DEPENDENCIES

      #-- FIN CODIGO CUSTOM --#

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}